### PR TITLE
feat: add new metadata for ground truth model

### PR DESCRIPTION
**Pull request by d-v-b**
this PR fleshes out a model for ground truth data that should accommodate both instance and semantic segmentations

cc @pattonw @neptunes5thmoon

### CODE REVIEW

**Comment by pattonw** [comment]
We're going to have Group (crop) -> list of (Group (pyramid) -> list of Array) right? The Group metadata here is for the crop, and nothing special goes in the pyramid metadata other than standard ome-zarr metadata?

Shouldn't the Instance/Semantic label go on the ArrayMetadata? You can definitely have both for a crop, i.e. semantic segmentation of all the organelles, but also an instance labelling of the cells.

**Comment by neptunes5thmoon** [comment]
After discussing with @axtimwalde, I'm back on team having the "unknown" label be `max_value - 1`. What we hadn't considered in our discussion is that there might be other special values that we have not thought of yet that might be relevant in the future. For example, if a crop is at the edge of a dataset, we might also want to include the "OUTSIDE" in each label array. Using the upper end of the value range would allow for more flexibility. We can still permit different data types, the `max_value` would just depend on the datatype. Thoughts?

**Comment by d-v-b** [comment]
after a long discussion with @neptunes5thmoon, this has evolved considerably. Here are example JSON metadata documents generated by parsing a single annotated volume:

crop-level metadata (zarr / n5 group)
```json
{
    "annotation": {
      "name": "Crop13",
      "description": "A crop",
      "protocol": {
        "url": "www.google.com",
        "class_names": [
          "ERES membrane"
        ]
      },
      "doi": null
    }
  }
```
group-level metadata (zarr / n5 group): 
```json
{
    "annotation": {
      "class_name": "ERES membrane",
      "description": "Endoplasmic reticulum exit site membrane",
      "created_by": [
        "Cellmap annotators"
      ],
      "created_with": [
        "Amira",
        "Paintera"
      ],
      "start_date": "2023-06-21T13:20:31.346669",
      "end_date": null,
      "duration_days": 10,
      "annotation_type": {
        "type": "semantic_segmentation",
        "encoding": {
          "absent": 0,
          "unknown": 255
        }
      }
```
scale-level metadata (zarr / n5 array)
```json
{
    "annotation": {
      "class_name": "ERES membrane",
      "histogram": {
        "absent": 998628,
        "unknown": 0
      },
      "annotation_type": {
        "type": "semantic_segmentation",
        "encoding": {
          "absent": 0,
          "unknown": 255
        }
      }
    }
```

**Comment by d-v-b** [comment]
I'm just going to merge this, and we can start playing with it

**Pull request merged**
