### PR TITLE
add new organelles classes

### PR DESCRIPTION
**Pull request by mzouink**
Missing class organelles used for cellmap

### CODE REVIEW

**Comment by mzouink** [comment]
@d-v-b  can you please merge

**Comment by d-v-b** [comment]
sure :)

**Comment by mzouink** [comment]
Thank you @d-v-b . is it automatically released in pypi ?

**Comment by d-v-b** [comment]
no, i haven't set that workflow up. I can push to pypi later tonight though, since I have some stuff I want to get out anyways

**Pull request merged**
