### PR TITLE
More v9 header fixes

### PR DESCRIPTION
**Pull request by trautmane**
Hi Davis - take a look and apply these changes if everything looks ok.

### CODE REVIEW

**Comment by d-v-b** [comment]
Looks great, thanks for fixing this!

**Comment by d-v-b** [comment]
@trautmane looks like the test fixtures folder wasn't added to version control, so I get a failing test. Could you add the fixtures folder?

**Comment by trautmane** [comment]
@d-v-b - it looks like everything is there to me (see https://github.com/janelia-cosem/fibsem-tools/pull/17/commits/7649004c8fc4dedb31c803218169e35c2f82ba9f ).  Am I misunderstanding something?

**Comment by d-v-b** [comment]
no, i'm the one who is confused -- tests are failing but the fixture is definitely present. i will figure it out. sorry for the noise.

**Pull request merged**
